# Generated by Django 4.2.5 on 2023-10-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversationmessage_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='text',
            new_name='body',
        ),
    ]
