# Generated by Django 4.2.5 on 2023-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_text_conversationmessage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
