# Generated by Django 4.2.5 on 2023-10-15 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_conversation_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-modified_at"]},
        ),
    ]
