# Generated by Django 4.2.5 on 2023-10-15 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_conversation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["modified_at"]},
        ),
    ]
