# Generated by Django 4.2.5 on 2023-09-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachement',
            new_name='attachment',
        ),
    ]
