# Generated by Django 4.2.5 on 2023-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_rename_user_comment_author_comment_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashtag", models.CharField(max_length=50)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-count"],
            },
        ),
    ]
