# Generated by Django 4.2.5 on 2023-09-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0003_alter_friendrequest_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
