# Generated by Django 4.2.5 on 2023-09-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0004_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('DECLINED', 'declined')], default='PENDING', max_length=10),
        ),
    ]
