# Generated by Django 4.2.5 on 2023-09-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0005_alter_friendrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friendship_requests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
